spring:
  application:
    name: Backend

  profiles:
    default: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-seconds: 1800
  refresh-token-validity-seconds: 604800

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
